### PR TITLE
Add support for element chaining (optional parent)

### PR DESCRIPTION
**Pull request by mradionov**
Current version queries `document` all the time. This PR adds an ability to use *uiSref* locator in element chains, which is normal for *Protractor*:
```js
element(by.css('#header')).element(by.uiSref('home.about')).element(by.css('.icon'))....
````

### CODE REVIEW

**Comment by crzrcn** [comment]
Thanks for taking the time to improve protractor-uisref-locator!

Minor feedback before I accept the PR:

* Use `parentElement` as the variable name for optional parent element. 
* Documentation should be updated to provide an example of new functionality, and to explain that the argument is optional.

Don't forget to squash any additional commits.

**Comment by mradionov** [comment]
I've seen your module [protractor-linkuisref-locator](https://github.com/crzrcn/protractor-linkuisref-locator) and there you tell in docs, that parent element should be passed explicitly to the locator. I wonder if it is the right way to do it, because Protractor [automatically passes](https://github.com/angular/protractor/blob/7e8d4fdb4e4084e5f92b05bd9014f73ac06827fe/lib/locators.js#L66) in a parent if there is any in the chain:

```
element(by.css('#header')).element(by.uiSref('home.about')).element(by.css('.icon'))....
//           ^                                  ^                          ^
// no parent, document             parent #header         parent ui-sref="home.about"
//    will be used                  will be used               will be used
```

So if we pass a parent explicitly, it will have custom parent as a second argument and auto-injected parent (if there is one), as a third argument of locator. Could you please clarify to me a bit the idea of passing a parent in a functional way.

Also I am not sure if it is a protractor bug, but when I want to use `element.all()` with a way of passing explicit parent, if fails with `RangeError: Maximum call stack size exceeded`:
````
element.all(by.uiSref('user', element(by.css('.parent')))); // error
element.all(by.uiSref('user', element(by.css('.parent')).getWebElement())); // works
````
Seems that Protractor is not always able to convert ElementFinder to webdriver.WebElement, which will be used in selenium, when custom locator gets injected on the page. I suppose the same bug exists in [protractor-linkuisref-locator](https://github.com/crzrcn/protractor-linkuisref-locator).

**Comment by crzrcn** [comment]
Good points. Also, I now notice why you chose the original wording of the optional element (that's how protractor itself does it). I guess that nullifies the first bullet on my previous comment. I'll think over the other stuff you said and get back to you.

**Comment by crzrcn** [comment]
My initial choice of passing in the parent element explicitly was probably out of ignorance or "fuck it, it works". I agree that it should be changed to be done how Protractor does it, by chaining. 

I'm wiling to declare the bug you mentioned as fixed if the chaining version works with `element.all`.

I also noted that Protractor expects the locator script to return an Array ([http://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.addLocator](http://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.addLocator)). This assumption can be broken by both of my modules. Another thing to fix on a separate issue.

**Pull request merged**
